### ISSUE TITLE
Determine west-based release strategy

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#106]
We mostly have a plan for tagging a west-based release as discussed in https://github.com/zephyrproject-rtos/west/issues/39#issuecomment-423629912.

The short story is:

1. Tag every project (zephyr gets v1.14.0, hypothetical-other-thing gets v1.14.0, etc.)
2. Set the revisions for each project in the manifest file to v1.14.0; tag the commit that does that v1.14.0 as well

Then you can do `west init --mr v1.14.0`.

I think the thing we did not realize is that this will not prevent users from continually getting updates to west itself! These may in turn be backwards incompatible with the v1.14.0 versions of things. So if the user ever runs 'west pull', say, that will update west itself, which is not safe.

This issue tracks resolving this; it's a blocker for Zephyr v1.14.

**Comment by tejlmand** [comment]
Today a manifest may look as:
```
# The default West manifest file to be used for Zephyr.

manifest:
  defaults:
    remote: upstream
    revision: master

  remotes:
    - name: upstream
      url: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
```

how about extending this with `west` reference, such as
```
# The default West manifest file to be used for Zephyr.

manifest:
  <same as today>
  projects:
    - name: zephyr

west:
  revision: v.1.14.0
```
that would allow us to keep the knowledge in one place.
and introduce the rule, that if the west revision cannot be found, then west defaults to `master`.

This would allow to place the west revision in the manifest, tag it, and verify everything, as well as it won't break in case an invalid revision for `west` is placed in manifest, e.g. because there is work in progress. (Although a warning should be presented in that case.)

One could then place 
```
west:
  revision: v1.x.99
```
during development to indicate upcoming release.
