### ISSUE TITLE
Can I use West without Zephyr?

### ISSUE THREAD

**Issue by abmurad** [zephyrproject-rtos/west#196]
I would like to ask if I can use west with another project. I installed west and I tried to follow the https://github.com/zephyrproject-rtos/west#using-a-custom-main-west
but I have not managed to get it to work.

west.yml file:
```
# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

west:
  url: https://github.com/zephyrproject-rtos/west
  revision: master

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/abmurad

  # The initial list of external projects is just Zephyr's net-tools
  # repository, which is useful for running the Zephyr networking
  # stack in QEMU.
  #
  # This will grow over time as external code is migrated into its own
  # repositories.
  projects:
    - name: sub-proj
      revision: 9573004ecf74f2b556bcf7c170d9c92c7aeff1f5

  self:
    path: meta-proj
    #west-commands: scripts/west-commands.yml
```
output:
```
Initialized empty Git repository in /tmp/user/1000/manifest_1m2zs7v2/.git/
WARNING: gnome-keyring:: couldn't connect to: /run/user/1000/keyring-O3cjy7/pkcs11: Connection refused
p11-kit: skipping module 'gnome-keyring' whose initialization failed: An error occurred on the device
From https://github.com/abmurad/meta-proj
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
e4ae0f5760ae7b524fa9a8566ca991339c35a99b refs/remotes/origin/master
Already on 'master'
Branch master set up to track remote branch master from origin.
Initialized empty Git repository in /home/abdullah/test_ws/meta-proj-test/.west/west/.git/
WARNING: gnome-keyring:: couldn't connect to: /run/user/1000/keyring-O3cjy7/pkcs11: Connection refused
p11-kit: skipping module 'gnome-keyring' whose initialization failed: An error occurred on the device
From https://github.com/zephyrproject-rtos/west
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.2.0rc1  -> v0.2.0rc1
 * [new tag]         v0.2.0rc2  -> v0.2.0rc2
 * [new tag]         v0.2.0rc3  -> v0.2.0rc3
 * [new tag]         v0.3.0     -> v0.3.0
 * [new tag]         v0.3.0rc1  -> v0.3.0rc1
 * [new tag]         v0.4.0     -> v0.4.0
 * [new tag]         v0.4.0rc1  -> v0.4.0rc1
 * [new tag]         v0.5.0     -> v0.5.0
 * [new tag]         v0.5.1     -> v0.5.1
 * [new tag]         v0.5.2     -> v0.5.2
28cb52e4317a9725dea48317a6a3cf6bbbb9612d refs/remotes/origin/master
Already on 'master'
Branch master set up to track remote branch master from origin.
Initializing in new directory meta-proj-test
=== Cloning manifest repository from https://github.com/abmurad/meta-proj, rev. master into /tmp/user/1000/manifest_1m2zs7v2 ===
cloning https://github.com/zephyrproject-rtos/west at revision master
=== Cloning west repository from https://github.com/zephyrproject-rtos/west, rev. master into meta-proj-test/.west/west ===
Traceback (most recent call last):
  File "/usr/local/bin/west", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/west/_bootstrap/main.py", line 454, in main
    init(wrap_argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/west/_bootstrap/main.py", line 227, in init
    bootstrap(args)
  File "/usr/local/lib/python3.4/dist-packages/west/_bootstrap/main.py", line 303, in bootstrap
    wrap(cmd)
  File "/usr/local/lib/python3.4/dist-packages/west/_bootstrap/main.py", line 438, in wrap
    west.main.main(argv)
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/main.py", line 505, in main
    args.handler(args, unknown)
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/main.py", line 293, in command_handler
    command.run(known_args, unknown_args)
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/commands/command.py", line 85, in run
    self.do_run(args, unknown)
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/commands/project.py", line 73, in do_run
    _inf(project, 'Creating repository for {name_and_path}')
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/commands/project.py", line 1177, in _inf
    log.inf('=== ' + _expand_shorthands(project, msg), colorize=True)
  File "/home/abdullah/test_ws/meta-proj-test/.west/west/src/west/log.py", line 61, in inf
    print(colorama.Fore.LIGHTGREEN_EX, end='')
AttributeError: 'AnsiCodes' object has no attribute 'LIGHTGREEN_EX'
```
