### ISSUE TITLE
Option for tracking branches instead of detached HEAD

### ISSUE THREAD

**Issue by hakonfam** [zephyrproject-rtos/west#217]
Add an option which allows users to specify that a given project should be checked out "directly". This means that instead of having DETACHED HEAD state in the git repository, the specified branch is checked out and set up to track the configured remote.

This is needed when working with large features in a distributed team.
In this situation, it is often desired to maintain and share development branches in which all commits are kept (ie no force pushing).

This should allow a developer to do the following:

```
cd west-root-project
git checkout feature-branch
west update
cd my-west-configured-repo
git status 
"Your branch is up to date with 'your_remote/feature-branch'."
# Do work
git add -u
git commit -sm "stuff"
git push
```

**Comment by tejlmand** [comment]
This is intended to facilitate downstream work, where several developers may share a branch.

I suggest adding additional setting to the schema for the project map, so that one may specify:
```
  projects:
    - name: myproject
      revision: branchname
      checkout: true
```

and with an appropriate error message in case someone writes:

```
  projects:
    - name: myproject
      revision: SHA / tag
      checkout: true
```

Note: this is an opt-in for downstream projects, as branches which are forced pushed might experience undesired behavior if this option is set.
