### ISSUE TITLE
west update prints error when used without zephyr

### ISSUE THREAD

**Issue by KaSroka** [zephyrproject-rtos/west#316]
When using west without zephyr there is an error printed during `west update`.

Please see full log below:

```
kasr@ns-kasr-linux ~/repos/temp-test % west init -m https://github.com/some/repo.git
=== Initializing in /home/kasr/repos/temp-test
--- Cloning manifest repository from https://github.com/some/repo.git, rev. master
Initialized empty Git repository in /home/kasr/repos/temp-test/.west/manifest-tmp/.git/
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/some/repo
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
617eef7d200d3e767924d6173ba88bd4732ab17c refs/remotes/origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Already on 'master'
=== Initialized. Now run "west update" inside /home/kasr/repos/temp-test.

kasr@ns-kasr-linux ~/repos/temp-test % west update
ERROR: no --zephyr-base given, ZEPHYR_BASE is unset, west config contains no zephyr.base setting, and no manifest project has path "zephyr"
=== updating other_repo (other_repo_dir):
--- other_repo: cloning and initializing
Initialized empty Git repository in /home/kasr/repos/temp-test/other_repo_dir/.git/
--- other_repo: fetching changes
remote: Enumerating objects: 51030, done.
remote: Total 51030 (delta 0), reused 0 (delta 0), pack-reused 51030
Receiving objects: 100% (51030/51030), 56.28 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (40173/40173), done.
From https://github.com/some/other_repo
 * branch              master     -> FETCH_HEAD
HEAD is now at 3a248f64 [nrf52840] add UART and BLE bootloader support (#4212)
--- other_repo: checked out 3a248f649acd16448c7f27fe7f17f6f0bb6696f6 as detached HEAD
=== updating another_repo (another_repo_dir):
--- another_repo: cloning and initializing
Initialized empty Git repository in /home/kasr/repos/temp-test/another_repo_dir/.git/
--- another_repo: fetching changes
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 275 (delta 169), reused 275 (delta 169), pack-reused 0
Receiving objects: 100% (275/275), 180.08 KiB | 950.00 KiB/s, done.
Resolving deltas: 100% (169/169), done.
From https://github.com/some/another_repo
 * branch            master     -> FETCH_HEAD
HEAD is now at c18c545 [style] remove support for python2 (#73)
--- another_repo: checked out c18c5459f9e4c376791cb6afaf5898c2548fee43 as detached HEAD
```

And here's my west.yml:
```
manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/some
  
  projects:
    - name: other_repo
      revision: master
      path: other_repo_dir
    - name: another_repo
      revision: master
      path: another_repo_dir

  self:
    path: repo_dir
```
