### ISSUE TITLE
Allow to execute post update script for every project

### ISSUE THREAD

**Issue by KaSroka** [zephyrproject-rtos/west#320]
Allow executing post-update scripts for every project.

```
manifest:
  ...
  projects:
    ...
    - name: test
      post-update: post-update.sh
```
Or
```
manifest:
  ...
  projects:
    ...
    - name: test
      post-update:
        - post_update1.sh
        - post_update2.sh
```
The script should be runned just after the update of the particular project and before next projects being updated. When multiple scripts are provided they should be executed in order of presence.
