### ISSUE TITLE
Support git submodules

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#365]
This issue tracks adding support for projects with git submodules to west.

The overall goal is to clone and update submodules on `west update` in addition to the projects that contain them.

**Comment by finikorg** [comment]
We have now project we want to add as a Zephyr module. It has submodule. At the moment we are investigating what is the best way of handling it. Support git submodules in west would help.

**Comment by carlescufi** [comment]
I suggest something like this in the manifest schema:

```
  projects:
    required: true
    type: seq
    sequence:
      - type: map
        mapping:
          # Project's unique name.
          name:
            required: true
            type: str
          submodules:
             required: false
             type: any
```

and then do something similar to what we have in the `import:` field so you could do:

```
submodules: true
```
or
```
submodules:
    name-allowlist:
        - submodule_1
        - submodule_2
```
or
```
submodules:
    name-denylist:
        - submodule_1
        - submodule_2
```
