### ISSUE TITLE
Add 'path-prefix' key in west import map

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#367]
Example syntax:

```
manifest:
  projects:
  - name: zephyr
    url: https://github.com/zephyrproject-rtos/zephyr
    import:
      directory: zephyr_projects
```

Semantics:

- the `zephyr` project, and all imported projects, have `zephyr_projects` as an additional path component. e.g. `zephyr_projects/zephyr` instead of `zephyr` as the path for `zephyr` project
- the `directory` value cannot escape the workspace, e.g. `directory: ../..` is an error
- the `directory` value is cumulative, e.g. if the imported manifest in turn does an import with `directory: foo`, then the combined `directory` is `zephyr_projects/foo`

Alternate suggested spellings for `directory`:

- `path`
- `path-prefix`

**Comment by mbolivar** [comment]
cc @henrikbrixandersen @tejlmand

**Comment by henrikbrixandersen** [comment]
LGTM. Personally I prefer `directory`.

**Comment by DenvE** [comment]
Directory is fine fo me too

**Comment by marc-cpdesign** [comment]
I'd love to see this implemented also !

I'll take whatever keyword I get for 'directory', but also consider some alternatives:
- folder
- destination
- destination-prefix
- base-prefix
- base-destination

(Having 'prefix' or 'base' in there appeals to me because the _actual_ destination is the path+name)

**Comment by marc-hb** [comment]
> (Having 'prefix' or 'base' in there appeals to me because the actual destination is the path+name)

Agreed, "directory" or "path" are super generic terms, way too vague when left alone.

Inspired by "destination" and trying to describe the action rather than the elusive nature, how about `into:`?

```
manifest:
  projects:
  - name: zephyr
    url: https://github.com/zephyrproject-rtos/zephyr
    import:
      into: all_imports/zephyr_clones/
```
By the way will this new prefix support more than one multiple directory level?

**Comment by mbolivar** [comment]
> By the way will this new prefix support more than one multiple directory level?

It should IMO.

**Comment by marc-cpdesign** [comment]
+1 for "into"
+1 for recursive/ multi-level import support

Let me know if I can help somehow.

**Comment by euripedesrocha** [comment]
I would like to have something like this. But I would prefer a syntax that adds a prefix to the defaults section of the manifest:
```yaml
defaults:
    path_prefix: prefix_path
```
My goal at this moment is to have only the projects I´m using by setting import as false.

**Comment by tejlmand** [comment]
Just a thought.
Today I can have the following in a manifest:

```
manifest:
  projects:
  - name: zephyr-project
    path: zephyr-upstream
    repo-path: zephyr
    remote: upstream
```
and now you suddenly add `directory` as a keyword, so a manifest could end up as:
```
manifest:
  projects:
  - name: zephyr-project
    path: zephyr-upstream
    repo-path: zephyr
    remote: upstream
    import:
      directory: zephyr_projects
```

mixing `path` and `directory` in our yaml is inconsistent, so simply for that reason I dislike directory.

In this case, `import-path` or `path-prefix` would fit better in current structure, as well as little more self-explaining.

And we would end up with:
```
manifest:
  projects:
  - name: zephyr-project
    path: zephyr-upstream
    repo-path: zephyr
    remote: upstream
    import:
      import-path: zephyr_projects
      path-prefix: zephyr_projects
```

**Comment by marc-hb** [comment]
> mixing path and directory in our yaml is inconsistent,

While I find path and directory both too generic, I think the difference between them is well defined: a path is (long story short) a list of nested directories. This definition is surprisingly consistent across languages:
https://docs.python.org/3/library/pathlib.html#accessing-individual-parts
https://perldoc.perl.org/File/Path.html
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html
https://en.cppreference.com/w/cpp/filesystem/path

Hence my earlier question about supporting multiple levels.

**Comment by tejlmand** [comment]
> > mixing path and directory in our yaml is inconsistent,
> 
> While I find path and directory both too generic, I think the difference between them is well defined: a path is (long story short) a list of nested directories. This definition is surprisingly consistent across languages:

I was more referring to the situation in the original proposal where the yaml could look as:
```
manifest:
  projects:
  - name: zephyr-project
    path: zephyr-upstream
    import:
      directory: zephyr_projects
```
in this case I personally fail to see why `path` is correct under `projects`, and `directory` would be correct under the `import`.
As I assume users can write:
```
    import:
      directory: imported_projects/zephyr_projects
```
then it seems to my the `path`-based keyword is still most correct, and what is already in use.
