### ISSUE TITLE
Support copying/linking files in manifest

### ISSUE THREAD

**Issue by tknapstad** [zephyrproject-rtos/west#388]
# Use case

I wish to add files to the top level west workspace, for instance a README or a simple Makefile to wrap commonly used west/cmake targets. Currently it's only possible to have folders at the top level.

Example of  workspace layout:
```
west-workspace
├── README      # <- copied/linked from application/
├── application
│   ├── README
```

# Suggested solution

Implement support for two new keywords in the `projects` section of a manifest:

- `copyfile <src> <dst>` 
- `linkfile <src> <dst>` 

Where `<src>` is relative to the path of the project being specified and `<dst>` is relative to the workspace.

Example manifest:
```
manifest:
  projects:
    - name: zephyr
      copyfile: README.rst ./
      linkfile: README.rst ./
```

**Comment by chrta** [comment]
This is also interesting for files like .editorconfig or .clang-format so the can be used from other sub-folders.

**Comment by mbolivar** [comment]
Hello, and thank you very much for taking the time to file an issue.

> It shall be possible to specify multiple `copyfile` and `linkfile` directives for each project.
> 
> Example manifest:
> 
> ```
> manifest:
>   projects:
>     - name: zephyr
>       copyfile: README.rst ./
>       copyfile: LICENSE ./
>       linkfile: west.yml ./
>       linkfile: VERSION ./
> ```

I believe YAML lists, e.g. as supported by the import name-whitelist and other similar manifest syntax, may be easier to use.

Example:

```yaml
manifest:
  # ...
  projects:
    - name: foo
      copyfile: README.txt .
    - name: bar
      copyfile:
        - Makefile .
        - README-makefile.txt .
```

I.e. `copyfile` and `linkfile` would accept either a string or a list of strings.

Thoughts?
