### ISSUE TITLE
Using West for generic, non-zephyr projects

### ISSUE THREAD

**Issue by ark-** [zephyrproject-rtos/west#473]
Is there a way to use this tool for managing a generic project?

I like the manifest file format. The idea of being able to just `west update` to pull in dependencies from multiple sources for a project could be quite useful to resolve dependencies.

If west isn't suitable but there are other tools which do this I am all ears.

**Comment by ark-** [comment]
Ok so I think I've figured it out from digging through the docs.

Directory structure:

``` 
my-project
    libraries
        west.yml
    <rest of my project files>
```

Where `west.yml` is something like:


``` yaml
remotes:
    - name: my_scm
      url-base: <url here>

defaults:
    remote: my_scm
projects:
    - name: first-dependency
      repo-path: dependency-name
      revision: 1.0.1
      path: libraries/dependency-name

```

Go into root directory:

``` cmd
west init -l libraries
```
