### ISSUE TITLE
Support use of `git worktree` in west

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/west#478]
Today, the manifest in Zephyr might contain multiple entries of the same repository, but in different versions (SHAs), such as:
- mcuboot for both Zephyr and TF-M
  https://github.com/zephyrproject-rtos/zephyr/blob/master/west.yml#L96-L98
  ```
    - name: mcuboot
      revision: 3fc59410b633a6d83bbb534e43aac43160f9bd32
      path: bootloader/mcuboot
  ```
  https://github.com/zephyrproject-rtos/zephyr/blob/master/west.yml#L147-L150
  ```
    - name: tfm-mcuboot # This is used by the trusted-firmware-m module.
      repo-path: mcuboot
      path: modules/tee/tfm-mcuboot
      revision: 1.7.0-rc1
  ```

- mbedtls in Zephyr and TF-M (mbedtls is cloned during build time (ninja), but there is work ongoing to see if could be improved):
  https://github.com/zephyrproject-rtos/zephyr/blob/master/west.yml#L93-L95 
   ```
    - name: mbedtls
      revision: 24d84ecff195fb15c889d9046e44e4804d626c67
      path: modules/crypto/mbedtls
  ```
  https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/96340fb6c0b7e31c2070e1f428ca24076d2700a6/trusted-firmware-m/lib/ext/mbedcrypto/CMakeLists.txt#L22-L23
  ```
            GIT_REPOSITORY https://github.com/ARMmbed/mbedtls.git
            GIT_TAG ${MBEDCRYPTO_VERSION}
  ```

This means that `west` will clone and update the same repository multiple times (mcuboot) instead of a single fetch.

If `git worktree` was used, then a single fetch would be enough, and the two paths would be sharing same repo but having different versions.

As example, we could have:
```
    - name: mcuboot
      revision: 3fc59410b633a6d83bbb534e43aac43160f9bd32
      path: bootloader/mcuboot
      worktrees:
        - name: tfm-mcuboot # This is used by the trusted-firmware-m module.
          path: modules/tee/tfm-mcuboot
          revision: 1.7.0-rc1
```
would allow to just fetch mcuboot once, but still allow for two different versions to be used for Zephyr and TF-M.

Similar improvement will be possible for mbedtls in future.
