### ISSUE TITLE
Let `west` determine revision for modules when the `import` is not declared

### ISSUE THREAD

**Issue by manoj153** [zephyrproject-rtos/west#554]
Can west determines modules revision when `import` is not specified?

### From zephyr doc:
The main advantage to using import is not having to track the revisions of imported projects separately. In the above example, using import means Zephyr’s module versions are automatically determined from the zephyr/west.yml revision, instead of having to be copy/pasted (and maintained) on their own.

#### My use-case:

I would want to specify the required modules. It is possible as of now, but it would be nice if `west` could figure the revision of the specified module. 

#### Example `west.yml`:

```
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v2.5.0
      west-commands: scripts/west-commands.yml
    - name: hal_st
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      path: modules/hal/stm32
      groups:
        - hal
    - name: cmsis
      path: modules/hal/cmsis
      groups:
        - hal

  self:
    path: NUCLEOH723
```
