### ISSUE TITLE
west update: remotes are not imported from submanifests

### ISSUE THREAD

**Issue by leocencetti** [zephyrproject-rtos/west#565]
We are migrating to `west` to manage our (private) project dependencies/submodules, but we are facing some difficulties integrating `west` in our GitLab CI workflow:  we need to use `HTTPS` remotes for CI pipelines (for authentication purposes), but we would like to keep using `SSH` locally.

It would be nice if remotes could be overridden way as projects, e.g. with a `00-ci.yml` sub-manifest, included only when needed. For example:
```yaml
# west.yml
manifest:
    version: "0.10"
    remotes:
        - name: origin
          url-base: git@gitlab.com:group
    defaults:
        remote: oi-origin
    projects:
        - name: moduleA
          path: modules/moduleA
          repo-path: moduleA.git
self:
    import: submanifests 
```
```yaml
# submanifests/00-ci.yml
manifest:
    version: "0.10"
    remotes:
        - name: origin
          url-base: https://gitlab.com/group
```
In this example, the `repo-path` for `moduleA` would resolve to:
- `git@gitlab.com:group/moduleA.git` for local workflows
- `https://gitlab.com/group/moduleA.git` for CI workflows

At the current stage, including the `00-ci.yml` file has no effect on the remote's `base-url` (always resolved to `SSH`).
The only solutions we could find are:
1. Re-declaring all the projects within the `00-ci.yml` manifest, with a non-negligible duplication cost.
2. Perform a manual substitution (`sed`) of the remote's URL before running `west update`
