### ISSUE TITLE
Add git-patch feature in west update

### ISSUE THREAD

**Issue by DonShogun** [zephyrproject-rtos/west#596]
In addition to revision, the configuration in west.yaml should also optionally takes patch and apply it after checkout on specified branch.

```
manifest:
  ...
  projects:
    ...
    - name: test
      revision: abcd12345dcba54321
      git-patch: path/to/test-001.patch
```
`west` should prepare all needed repositories in ready-to-build state. This should be limited to simple git commands e.g.: `git apply  path/to/test-001.patch`
This change is motivated by faster bug fixing without waiting for official releases, adding custom settings and inner-project integrations.
