### ISSUE TITLE
west update loops infinitely over the first repository

### ISSUE THREAD

**Issue by tomi-font** [zephyrproject-rtos/west#690]
> $ west update
> === updating sdk-nrf (nrf):
> HEAD is now at 8da54fd6e manifest: nrf_modem v2.4.0
> === updating sdk-nrf (nrf):
> HEAD is now at 8da54fd6e manifest: nrf_modem v2.4.0
> === updating sdk-nrf (nrf):
> HEAD is now at 8da54fd6e manifest: nrf_modem v2.4.0
> === updating sdk-nrf (nrf):
> HEAD is now at 8da54fd6e manifest: nrf_modem v2.4.0
> [...]

This loop goes on forever.
Happens with version 1.0.0, but also with a manual build from https://github.com/zephyrproject-rtos/west/tree/v1.2.99.

Contents of `.west/config` (located alongside `my_dir` and `nrf`):
```
[manifest]
path = my_dir
file = west.yml

[zephyr]
base = zephyr
```

Contents of `my_dir/west.yml`:
```
manifest:
  defaults:
    remote: ncs

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      path: nrf
      remote: ncs
      revision: 8da54fd6e4590cffc3cf7e2d1e6af85b23b549c2
      import: true
```
