### ISSUE TITLE
Allow import of optional projects from manifest file

### ISSUE THREAD

**Issue by pdgendt** [zephyrproject-rtos/west#696]
**Is your feature request related to a problem? Please describe.**
When using out-of-tree applications, I would like to add optional projects from the application's manifest file.
For example, I use `nanopb` which is an optional package in `zephyr`.

**Describe the solution you'd like**
It would be nice to support `project-filter: [+nanopb]` directly from the manifest file.

Currently I have to configure a workspace with:

```shell
west config manifest.project-filter -- +nanopb
```

While my `west.yml` already has it in the `name-allowlist`:

```yaml
manifest:
  self:
    path: app

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      revision: main
      remote: upstream
      import:
        name-allowlist:
          - cmsis
          - hal_atmel
          - nanopb
          - picolibc
```

**Describe alternatives you've considered**
I can add `group-filter: [+optional]` to the manifest file, but this can lead to more projects being updated than necessary if I would use `import: true` instead of an allow list.
