### ISSUE TITLE
west manifest freeze/resolve will lose submodules information

### ISSUE THREAD

**Issue by yvesll** [zephyrproject-rtos/west#739]
the project in raw west.yml
```yaml
  - name: test_repo
    path: manifest_repo/test_repo
    revision: main
    submodules:
    - path: modules/test_module
```
And run `west manifest --resolve -o freeze.ym`
freezed west.yml
```yaml
  - name: test_repo
    path: manifest_repo/test_repo
    revision: main
```
The submodules key gone.
Not sure whether this field was ignored in project's as_dict api: https://github.com/zephyrproject-rtos/west/blob/49f0a101df45ea735437bd388606a1219d9e76f5/src/west/manifest.py#L866
