### ISSUE TITLE
West doesn't find extension commands when run in a workspace without additional modules

### ISSUE THREAD

**Issue by kieranwlc** [zephyrproject-rtos/west#772]
**Describe the bug**

When running west within a workspace that only contains zephyr and no additional modules, west doesn't find the extension commands in /scripts/west_commands.yml. E.g. 'zephyr-export.'

**To Reproduce**

1. Initialise a workspace with a manifest that just contains zephyr and no additional modules:
E.g.
app/west.yml
```
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
```

```
west init -l app
west update
```
2. Run west or one of the west extension commands
`west help`
`west zephyr-export`

**Expected behavior**

West should be able to detect and run the extension commands in /zephyr

**Impact**

Annoyance

**Logs and console output**

```
west: unknown command "zephyr-export"; workspace {workspace_path} does not define this extension command -- try "west help" and "west -vv status"
```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: just Zephyr
 - v4.0.0

**Comment by pdgendt** [comment]
You didn't import anything from the project, but you could add the `west-commands` entry manually

```yaml
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      west-commands: scripts/west-commands.yml
```
