### ISSUE TITLE
`west init` gives wrong config `path` for a manifest file in nested directories

### ISSUE THREAD

**Issue by fouge** [zephyrproject-rtos/west#774]
when initializing my workspace, i want the manifest file to be located **more than one** level below the west top dir, in `orb/private/west.yml`

```
.
├── .west
├── bootloader
│   └── mcuboot
├── modules
│   ├── ...
├── orb
│   ├── private/west.yml
│   └── public
└── zephyr
```

When initializing with `cd orb && west init -l --mf private/west.yml .`, the west config created is:
```
[manifest]
path = orb
file = private/west.yml
```

but then [zephyr_module.py](https://github.com/zephyrproject-rtos/zephyr/blame/main/scripts/zephyr_module.py) from Zephyr 4.0 fails because the manifest isn't in `orb` but `orb/private`.

If I modify `.west/config` manually, to have `path = orb/private`, then it works.

Would it be possible to have the `path` points to the manifest directory, and `file` only take the name of the west file?

**Comment by pdgendt** [comment]
You ~can~ make the manifest project path explicit.

```yaml
manifest:
  self:
    path: orb/private
```

EDIT: Ah the project is `orb`, nvm

**Comment by fouge** [comment]
here is the manifest
```
manifest:
  remotes:
    - name: worldcoin
      url-base: git@github.com:worldcoin
  defaults:
    remote: worldcoin
  group-filter: [+internal]
  projects:
    - name: orb-firmware
      revision: ...
      import:
        name-allowlist:
          - zephyr
          - ...
      path: orb/public
  self:
    path: orb/private
```
